{
 "title": "Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime in minutes",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((time() - process_start_time_seconds) / 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime in days",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((time() - process_start_time_seconds) / 60 / 60 / 24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Code",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (http_request_duration_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Endpoint Avg Bucket Sumary in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket",
     "legendFormat": "{{code}}  {{method}}  {{route}} | {{le}} |"
    }
   ]
  },
  {
   "title": "API Endpoint Avg Request Sumary in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "{{code}} | {{method}} | {{route}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "process_cpu_user_seconds_total", "legendFormat": "{{__name__}}: {{job}}" }
   ]
  }
 ]
}