name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Ensure Docker is ready
        run: |
          docker --version
          docker ps

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Run tests with debug logs
        run: pnpm vitest --config ./vitest.config.ts run --reporter verbose

      - name: Run build
        run: pnpm run build
