name: Deploy
on:
  push:
    paths:
      - tools/prisma/schema.prisma
    branches:
      - main

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set up migration files
        run: |
          pnpm exec prisma generate
          pnpm exec prisma migrate reset --force
          pnpm exec prisma migrate dev -n action --create-only

      - name: Apply all pending migrations to the database
        run: |
          pnpm exec prisma migrate deploy
          node tools/scripts/apply-vector-migration.js
