name: Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run semantic-release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
